include <layouts/l9-pinhole-test.scad>

INCH = 25.4;
CEIL_CLEARANCE = 600;
NUM_PHONES = 3;
DRAW_RANDOM = false;


PANE_WIDTH = 10 * INCH;
PANE_HEIGHT = 8 * INCH;
PANE_THICKNESS = 2;

FRAME_PADDING = INCH / 4;

FRAME_WIDTH = PANE_WIDTH + 2 * FRAME_PADDING;
FRAME_HEIGHT = PANE_HEIGHT + 2 * FRAME_PADDING;
FRAME_THICKNESS = INCH / 4;

CASE_THICKNESS = 1.5;
WALL_THICKNESS = 3;

BOARD_HOLDER_MARGIN = 2; //temp to address poor fit. ===2


d = 0.01;
d2 = 2 * d;
wiggle = 1;
